### ISSUE TITLE
privileged mode needed?

### ISSUE THREAD

**Issue by guillaumedsde** [binhex/arch-qbittorrentvpn#1]
Hi, I was wondering why privileged mode was needed.
I tried starting the container without privileged mode and it did not work, and the logs were not very helpful as to why, even with the debug flag enabled.

Which parts of it require privileged mode?

**Comment by binhex** [comment]
You need to have as a minimum net cap admin privileges for openvpn but due to qBitTorrent application itself you also need to elevate that further to privileged.

**Comment by binhex** [comment]
Yeah you and me both, best asking on the qBitTorrent GitHub repo.

**Comment by guillaumedsde** [comment]
alright haha, in any case, thank you for this container, it is much appreciated

**Comment by nemchik** [comment]
Just found this wondering the same thing myself. Has anyone dug in further already and found an answer?

**Comment by nemchik** [comment]
Just an additional note: I tried with net_admin and without privileged and found that it looked like the WebUI started but logins would fail. Swapping back to privileged resolved the issue. The biggest difference I see (on the surface, I'm no expert) with the LSIO image vs this one is they are using the s6 overlay and do not add `--daemon` to the `/usr/bin/qbittorrent-nox` command. I'm not sure how to even begin trying to test what might work because I have not build docker images on my own yet.

**Comment by guillaumedsde** [comment]
> Just an additional note: I tried with net_admin and without privileged and found that it looked like the WebUI started but logins would fail. Swapping back to privileged resolved the issue. The biggest difference I see (on the surface, I'm no expert) with the LSIO image vs this one is they are using the s6 overlay and do not add `--daemon` to the `/usr/bin/qbittorrent-nox` command. I'm not sure how to even begin trying to test what might work because I have not build docker images on my own yet.

Yep, the S6 overlay probably handles the "running as a non root user" bit. I gave a quick look at the code, @binhex  any reason you use user `nobody` rather than an actual user?

**Comment by fryfrog** [comment]
> Yep, the S6 overlay probably handles the "running as a non root user" bit. I gave a quick look at the code, @binhex any reason you use user `nobody` rather than an actual user?

The user inside shouldn't matter, it is just a name. The UID/GID are what really matter. Many containers use `abc` on the inside. What makes you think `nobody:nobody` is the issue?

**Comment by guillaumedsde** [comment]
> > Yep, the S6 overlay probably handles the "running as a non root user" bit. I gave a quick look at the code, @binhex any reason you use user `nobody` rather than an actual user?
> 
> The user inside shouldn't matter, it is just a name. The UID/GID are what really matter. Many containers use `abc` on the inside. What makes you think `nobody:nobody` is the issue?

I'm unsure whether this is the issue, but I sumbled upon this: https://github.com/qbittorrent/qBittorrent/wiki/Setting-up-qBittorrent-as-a-daemon-on-CentOS-7

I'm not sure if in this example its a Cent OS service thing or a qbittorent thing, but at one point its stated 
> ... change <username> to the user you want to run qbittorrent with. Note that you can't run as user nobody.

**Comment by guillaumedsde** [comment]
perhaps this issue should not be closed @binhex ?

**Comment by binhex** [comment]
Reopened, but no obvious fix at the mo.

**Comment by binhex** [comment]
getting bored looking at this issue, no resolution/insight so no point to keeping this open really, closing off for good.

**Comment by guillaumedsde** [comment]
Understood, I've briefly looked around as well, I'm bewildered as to why
```yaml
cap_add:
        - NET_ADMIN
```
does not work. As a workaround for getting qbittorrent and openvpn working in docker, I'm currently using the trick higlighted here: https://pgblitz.com/threads/howto-use-single-and-central-vpn-container-for-all-your-other-apps.2563/

using https://github.com/haugene/docker-transmission-openvpn and the official lsio qbittorrent docker image

Note however that it is not an ideal solution since if for whatever reason the "master" container has connectivity issues, network comes offline for the qbittorrent container....


When I have some time, I'll try and port Haugene's container to qbittorrent: https://github.com/haugene/docker-transmission-openvpn

**Comment by hotio** [comment]
FYI, I'm running this on unraid with `--cap-add=NET_ADMIN` and NOT privileged. I'm not seeing any issues...

**Comment by binhex** [comment]
@hotio thanks for letting me know that's interesting that it now works correctly without running privileged, I will run a test

**Comment by brintal** [comment]
Chiming in here.
Currently I'm running a custom setup using dperson/openvpn-client and linuxserver/qbittorrent. I'm trying to simplify my setup and heard good things about this image.
But the privileged flag scares me. I had no problems with using only the NET_ADMIN capability on my openvpn container, hence I don't understand why this image needs it.
@binhex could you already test and verify that it runs without privileged?

**Comment by binhex** [comment]
did a quick test and it starts and operates just fine with only --cap-add=NET_ADMIN so whatever was cuasing the requirement for privileged looks to now be resolved.

i shall update the template and readme for the standard --cap-add=NET_ADMIN option as opposed to privileged.

**Comment by guillaumedsde** [comment]
Good news :) thanks for looking into it
