### ISSUE TITLE
Issues with tun device

### ISSUE THREAD

**Issue by ryaniskira** [binhex/arch-qbittorrentvpn#10]
I am migrating from LSIO's qBittorrent Docker container as I find the utility of OpenVPN, qBittorrent, and Privoxy all in one container to be useful, but in running this container I always get hung up on this error:
```
2019-02-27 12:38:57,649 DEBG 'start-script' stdout output:
Wed Feb 27 12:38:57 2019 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
Wed Feb 27 12:38:57 2019 Exiting due to fatal error
```

OpenVPN is installed on the host (which is Arch Linux) and my docker run command is listed (it's a bit messy as I am simply testing before I migrate everything) here:
`docker run --detach --privileged=true --name=qBittorrent-Test -p 6000:6000 -p 6001:8118 -p 6002:6881 -p 6002:6881/udp -v /mnt/Media/Sandbox/qBittorrent-Test/Torrents:/downloads -v /mnt/Media/Sandbox/qBittorrent-Test/Data:/config -v /etc/localtime:/etc/localtime:ro -e VPN_ENABLED=yes -e VPN_USER=lolno -e VPN_PASS=lolno -e VPN_PROV=pia -e STRICT_PORT_FORWARD=yes -e ENABLE_PRIVOXY=yes -e LAN_NETWORK=192.168.1.0/24 -e NAME_SERVERS=209.222.18.222,37.235.1.174,1.1.1.1,8.8.8.8,209.222.18.218,37.235.1.177,1.0.0.1,8.8.4.4 -e DEBUG=false -e WEBUI_PORT=6000 -e UMASK=755 -e PGID=993 -e PUID=1000 binhex/arch-qbittorrentvpn`

**Comment by fryfrog** [comment]
I have `--device=/dev/net/tun` in my run command, I swear it was in the documentation... but when I just looked, it isn't.

Also, you can use
\`\`\`
Stuff here
\`\`\`

to format your run line better.

**Comment by binhex** [comment]
@fryfrog its not in the docs as its not normally required actually, you can usually get away with simply generating it as part of the startup procedure, see link 148 in the following file:-
https://github.com/binhex/arch-int-openvpn/blob/master/run/root/start.sh

**Comment by ryaniskira** [comment]
@fryfrog Adding that switch manually worked for me. Everything is starting up just fine now.

**Comment by fryfrog** [comment]
Humm, good point. My rtorrent containers don't have it. Let me try removing it from my qB.

**Comment by ryaniskira** [comment]
@binhex My issue is resolved but I do have a question, when there are multiple OpenVPN profiles in the directory what's the selection behavior? Is it random or does it go down the list until one connects?

**Comment by fryfrog** [comment]
I'd bet it just uses the first one that shows up in something like `ls *.ovpn`. :)

**Comment by binhex** [comment]
Correct @fryfrog

**Comment by ryaniskira** [comment]
No use leaving an issue open when it's resolved.
