### ISSUE TITLE
Bind network interface in settings?

### ISSUE THREAD

**Issue by silly-questions** [binhex/arch-qbittorrentvpn#100]
Hello, first of all, I just want to say thank you for this awesome bit of software.  it's took me a while to get it installed and setup on unraid, (due to being very new to unraid and dockers) but I think I have got there in the end!   I am using openvpn, with the openvpn config file provided by my vpn in this docker.  If i use the console to send a curl command, I get the vpn ip address, so i think I have set everything up ok. 

I just have a quick question on binding the network interface when using the VPN.  Is it ok to still bind the network interface in the qbittorrent advanced options?  Or will this break something?  i understand there are iptables which shoukld prevent a leak, but I was thinking if i bound it to the vpn, if the vpn dropped out, qbittorrent wouldn't have any internet access to use at all.  Is this not necessary with this docker due to how the docker works in unraid, or is it still a good idea?  I have "lo", "tun0", and "eth0" listed in the network interface.  Am i correct in thinking "tun0" would be the vpn connection and the one to use?

thanks for any help anyone can give 👍

**Comment by silly-questions** [comment]
Hello, thanks for getting back to me.  I only asked because when I looked, it was set to any adapter.  I have changed it to tun0, hope that's the right one?  If i use curl in the console for qbittorrentvpn. it gives me my vpn ip still, so think thats right :)

**Comment by binhex** [comment]
tun0 will be the right adapter if you are using openvpn, for wireguard its wg0.
