### ISSUE TITLE
DNS Resolution Problem while Docker is starting

### ISSUE THREAD

**Issue by keturo** [binhex/arch-qbittorrentvpn#103]
I added a local DNS Server to the connection to start the initial connection with the local dns server.
If i allow now the connection from the container to my local DNS server and block the connection to the public one (cloudflare, pia dns server, etc) the connection needs a lot of time to start.
Could this be optimized?

**Comment by keturo** [comment]
Edit:
As i see it tries on every DNS server to get a response, so reducing the DNS Server to only 2 or 3 makes everything faster.
Best way would be if it uses the local address first.

**Comment by binhex** [comment]
Local DNS is blocked using iptables to prevent any potential IP leakage I am not planning on changing this

**Comment by keturo** [comment]
The interesting thing, the local dns is working for me when i set this up in the container with the variable. But it need some time to resolve the host name.
I understand if you dont wanna enable this. I only like to use an encrypted DNS instead of udp/53 to communicate
