### ISSUE TITLE
Web UI stopped working after update

### ISSUE THREAD

**Issue by zachoooo** [binhex/arch-qbittorrentvpn#107]
I don't know if you can help with this, but I just updated my docker container and all of my torrents disappeared. I didn't change anything other than running update with Unraid. Have you heard of something like this happening or know how to recover? My files are still there, but they aren't seeding.

EDIT: I just tried connecting with qBittorent remote on my phone and it was actually working. Nothing was lost and everything is still seeding, but the web endpoint I use for accessing qBittorrent doesn't seem to be working.  Do you know if anything changed related to that?

**Comment by r0arkin** [comment]
Do you have a backup of your qbittorrent.config? 

I have this issue from time to time where the config seems to be overwritten to a blank config and Qbit reverts to a fresh install. 

If you have a backup of the config, you would need to stop the container, mv the current one to _old or whatever (to back it up just in case) and then copy over the backup config. Then start up Qbit again and everything should be back to normal.

**Comment by zachoooo** [comment]
I'm not even sure if this is an issue with qBittorent, it may be possible that something with the networking changed since I access it through a reverse proxy. I'm just gonna close this out lol.
