### ISSUE TITLE
Stop defining volumes in Dockerfile

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-qbittorrentvpn#108]
Hey @binhex, how would you feel about dropping the defined volumes in your Dockerfile? In this one, you define `/data` and `/media` for example. That means that if someone *doesn't* use those paths, Docker creates volumes for them. Ideally, I'd ask you to do them more like @hotio, with *no* volumes defined *or* suggested... but I'd settle for not defining them like LSIO has done.

**Comment by binhex** [comment]
done (all images).
