### ISSUE TITLE
Does OpenVPN Restart on Connection Failure?

### ISSUE THREAD

**Issue by PacketShepard** [binhex/arch-qbittorrentvpn#13]
Hi Binhex,

I was using another qbittorrent with OpenVPN docker and it doesn't seem to have the daemon scripts right to restart the openvpn connection when the keepalives fail. I end up having to grab a shell in the container and manually restart it or restart the whole container.

Does your container handle keepalive and connect failures gracefully by restarting the OpenVPN connection?

Thanks.

**Comment by binhex** [comment]
In a  word yes it will auto restart qbittorrent and OpenVPN on crash or disconnection of the tunnel
