### ISSUE TITLE
Latest Won't Accept Incomplete Torrents Path

### ISSUE THREAD

**Issue by x86txt** [binhex/arch-qbittorrentvpn#131]
Hi - first, thanks for all your hard work. This container has been a godsend for me.

In the latest version of the container released 2 days ago (DIGEST:sha256:690fabaf95aaec04ebc0d272eede69a88c20585dccc53ddcab73f96791cef5e4) the torrent incomplete folder (Keep incomplete torrents in:) cannot be changed, it seems to be hardcoded to something like qBittorrent/data/temp.

If I roll back to the previous release (4.4.2-1-01), the path can be set properly again.

**Comment by vinaykapadia** [comment]
Can confirm. It's still happening with the latest. This is what I have set, and I can't change it:

![image](https://user-images.githubusercontent.com/17637030/169921116-a5a8192a-ff99-4c75-a473-99f884ed1b6a.png)

I can edit the box, but it doesn't stick after clicking Save.

**Comment by x86txt** [comment]
Same here. :(

**Comment by vinaykapadia** [comment]
@x86txt looks like the latest update fixed it!

**Comment by x86txt** [comment]
> @x86txt looks like the latest update fixed it!

It did for me too, thanks!

**Comment by x86txt** [comment]
Latest version fixes it. Thanks binhex.
