### ISSUE TITLE
Client shows "Unauthorized" 

### ISSUE THREAD

**Issue by temelj** [binhex/arch-qbittorrentvpn#135]
qbittorrent client webpage opens but shows only "Unauthorized".

**Comment by tuur29** [comment]
I had the same issue after updating to the latest version.
It seems like my config file was reset because going back to the previous version also showed this behavior. I was able to login with the default username/password (`admin/adminadmin`) and needed to redo all settings.

**Comment by temelj** [comment]
Solution: 
https://www.truenas.com/community/threads/issue-accessing-qbittorrent-web-ui.91784/

Try disabling Host Header Validation.

Open a Shell in your qBittorrent jail, and edit the file `/.config/qBittorrent/qBittorrent.conf`

Change the value from
`WebUI\HostHeaderValidation=true`
to
`WebUI\HostHeaderValidation=false`
