### ISSUE TITLE
STRICT_PORT_FORWARD=yes causes PIA connection to fail

### ISSUE THREAD

**Issue by OpieO1** [binhex/arch-qbittorrentvpn#140]
I have noticed that if I have the STRICT_PORT_FORWARD enabled in my docker compose configuration it prevents PIA from connecting:

```
    - VPN_PROV=pia
    - VPN_CLIENT=openvpn
    - STRICT_PORT_FORWARD=yes
 ```
I will see the following in the logs:
```[warn] Unable to successfully download PIA json payload from URL 'https://10.6.112.1:19999/getSignature' using token _'obfuscated'_```

As soon as I set 
```
    - STRICT_PORT_FORWARD=no
 ```
The container starts properly. I suspect that PIA may have changed their getSignature API, but I'm not sure what to validate to verify this.

**Comment by binhex** [comment]
what endpoint are you connecting to?, not all pia endpoints support port forwarding.

**Comment by OpieO1** [comment]
I should have captured the full logs, but I believe I was trying with ca-vancouver.privacy.network. I've tried with remote ca-toronto.privacy.network 1198 and I no longer see the behavior so I'll close the issue. Thank you for the quick response.
