### ISSUE TITLE
Issue with 

### ISSUE THREAD

**Issue by xipdk** [binhex/arch-qbittorrentvpn#143]
Latest version giving me this error at start:

Start container qbittorrent failed: {"message":"OCI runtime create failed: container_linux.go:367: starting container process caused: exec: \"/usr/bin/tini\": stat /usr/bin/tini: no such file or directory: unknown"}.

The earlier version works fine.

**Comment by thaindq** [comment]
I'm having the same issue. Running on DSM7. Going back to 4.4.4-1-01 works.

**Comment by ChiffX** [comment]
Also having the same issue on DSM7, and going to 4.4.4-1-01 per @thaindq's suggestion worked
