### ISSUE TITLE
Error egrep.

### ISSUE THREAD

**Issue by jodiekurnia** [binhex/arch-qbittorrentvpn#147]
2022-11-05 09:57:46,847 DEBG 'start-script' stderr output:
egrep: warning: egrep is obsolescent; using grep -E

**Comment by codymhorton** [comment]
+1 Woke up to this issue this morning, rolled back to 4.4.5-1-01 and it works again. Seems the latest update broke something.

**Comment by jeff15110168** [comment]
> +1 Woke up to this issue this morning, rolled back to 4.4.5-1-01 and it works again. Seems the latest update broke something.

how do i roll back? I'm also having issues

**Comment by kmr2319** [comment]
The egrep message appears to be a warning - likely innocuous.

I suspect this is the problem:
```
2022-11-05 23:45:57,441 DEBG 'start-script' stderr output:
sort: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

2022-11-05 23:45:57,442 DEBG 'start-script' stderr output:
/usr/sbin/wg-quick: line 338: echo: write error: Broken pipe
```

Hitting image via console and attempting to run sort returns the same error. 

line 338 in /usr/sbin/wg-quick calls sort.

As mentioned in previous comments, rolling back resolves the problem. sort works properly as well.

**Comment by martabal** [comment]
It seems to be fixed

**Comment by binhex** [comment]
fixed, issue was arch linux ripped out libcrypto 1.1 which wireguard relies on.
