### ISSUE TITLE
Add ADDITIONAL_PORTS argument as in arch-sabzndbvpn

### ISSUE THREAD

**Issue by grantbey** [binhex/arch-qbittorrentvpn#15]
### Problem statement
In order to allow connections to/from other local services, additional `iptables` rules need to be added. The primary use case for this would be to allow NzbToMedia scripts to call Radarr/Sonarr and for those applications to respond. Currently, the `iptables` rules block these connections and the NzbToMedia scripts fail.

The arch-sabnzbdvpn container has the `ADDITIONAL_PORTS` variable which allows for exactly this use-case. I'd like to see it here too.

### Solution
I've solved the issue on my end, but it's a hacky workaround and it's only persistent-ish - that is, it won't survive a container rebuild.

In essence, I customized the `iptables` rules that are instituted at container startup and using a similar `ADDITIONAL_PORTS` variable as the arch-sabnzbdvpn container.

#### My process is as follows:

1. I added the `ADDITIONAL_PORTS` variable to my container with the value `8989,7878` for Sonarr and Radarr, respectively.

2. I copied `/root/iptable.sh` to `/config/iptable.sh` and added the following changes:
    lines 102-103:
    `# accept input to qbittorrent api from radarr and sonarr`
    `iptables -A INPUT -i "${docker_interface}" -s "${lan_network_item}" -p tcp -m multiport --sport "${ADDITIONAL_PORTS}" -j ACCEPT`

    lines 159-160:
    `# accept output to radarr and sonarr from qbittorrent api`
    `iptables -A OUTPUT -o "${docker_interface}" -d "${lan_network_item}" -p tcp -m multiport --dport "${ADDITIONAL_PORTS}" -j ACCEPT`

3. Upon rebuilding the container (e.g. after updating or changing values on the Unraid WebUI) I run:
    `docker exec -it binhex-qbittorrentvpn cp /config/iptable.sh /root/iptable.sh && docker restart binhex-qbittorrentvpn`

### Next steps
I'd be happy to submit a pull-request for this change if it's acceptable. It's implemented _slightly_ differently than in arch-sabnzbdvpn, insomuch as the `iptables.sh` script adds a single rule with the `iptables` `multiport` module instead of looping through the comma-separated list of ports and adding a new rule for each one. I'd be happy to implement the arch-sabnzbdvpn version if that would be preferable. It does occur to me that my current implementation doesn't specifically catch the situation wherein `ADDITIONAL_PORTS` is not specified, but that is easy enough to add.

I'd love to see this implemented natively so that I wouldn't have to run the `cp` command on each container rebuild.

**Comment by joshkay** [comment]
Any chance to have this implemented?  Looking to setup sonarr / radarr with this but the connection fails.

**Comment by joshkay** [comment]
Or possibly another way to connect the two services together?

**Comment by binhex** [comment]
this was done yesterday, pull down the latest image and create the env var as per the readme.
