### ISSUE TITLE
Show connected IP address in webui

### ISSUE THREAD

**Issue by mjeshurun** [binhex/arch-qbittorrentvpn#152]

**Comment by mjeshurun** [comment]
Hi Friends, 
Since this qBittorrent app is supposed to connect us using a VPN, it would be very useful if the webui could display the actual IP address qBittorrent is using, so that we can always make sure our traffic is passed thorough the VPN and not using our ISP IP address. 
Is this a feature the developers can add?

**Comment by binhex** [comment]
It's not something I can do I don't develop the app you need to ask on the qbittorent repo or forum forum
