### ISSUE TITLE
egrep in start-script is obsolete

### ISSUE THREAD

**Issue by reticle5** [binhex/arch-qbittorrentvpn#159]
Hadn't seen this logged anywhere. I get the following messages in the docker logs when starting the container.

```
qbittorrent    | 2023-01-16 13:26:13,462 DEBG 'start-script' stderr output:
qbittorrent    | egrep: warning: egrep is obsolescent; using grep -E

```
Something to add to the list of tweaks for future versions.

**Comment by binhex** [comment]
already been fixed, this will take effect on the next image build:- https://github.com/binhex/arch-int-vpn/commit/27162b3b0629fa7d734389d9d0bcb0cd7abc6496
