### ISSUE TITLE
QBITTORRENTVPN_PORT_6881=6881

### ISSUE THREAD

**Issue by mouzzampk2014** [binhex/arch-qbittorrentvpn#16]
Hi,
Do I need to use 6881 in Connections Listening Port?

![3](https://user-images.githubusercontent.com/44548525/56080010-992fe600-5df3-11e9-9d9a-a0d319ecb107.JPG)

As you can see I changed the listening port and forward that port on VPN provider and its working perfectly but in my docker compose I didn't change the 6881=44042. I left it as it is?

```QBITTORRENTVPN_ENABLED=true
QBITTORRENTVPN_BACKUP_CONFIG=true
QBITTORRENTVPN_NETWORK_MODE=
QBITTORRENTVPN_PORT_6881=6881
QBITTORRENTVPN_PORT_8080=8085
QBITTORRENTVPN_PORT_8118=8118
QBITTORRENTVPN_ENABLE_PRIVOXY=no

Shall I change the port 6881=44042 in compose file or just change it via Web UI? Reason is my downloading speed is very slow and I am trying to rectify the issue :)

Thank you

**Comment by mouzzampk2014** [comment]
I tried few different VPN configurations but speed I'm reaching very low.
Is it possible to increase cpu resources?

Thank you

**Comment by binhex** [comment]
unless you are limiting docker then it will use all resources available on the host so no there is no way of increasing CPU resources

**Comment by mouzzampk2014** [comment]
Thank you so much I will just try to reduce VPN encryption that might help
:)

Thanks again

**Comment by mouzzampk2014** [comment]
I need change my listening port to something else. Currently set by default is 6881 and I am using qbittorrentvpn enabled on. Do I need to change the port in UI or .conf? Thank you

**Comment by binhex** [comment]
the ui should change the port in the conf, so use the ui

**Comment by mouzzampk2014** [comment]
Thank you so much :)
