### ISSUE TITLE
"[crit] iptables kernel module 'ip_tables' not available, exiting script" on latest version

### ISSUE THREAD

**Issue by wieluk** [binhex/arch-qbittorrentvpn#165]
I am getting this error after updating to latest version. Do you know what could cause it? It works fine on the previous image:  binhex/arch-qbittorrentvpn:4.5.1-1-01.

**Comment by binhex** [comment]
Update to latest

**Comment by wieluk** [comment]
What? This happens when updating to latest ... the last version before latest works.

**Comment by wieluk** [comment]
Seems to work now sorry don't know what the problem was.
