### ISSUE TITLE
Module iptable_mangle not found in directory /lib/modules/5.16.0-0.bpo.4-amd64

### ISSUE THREAD

**Issue by XenoBIT78** [binhex/arch-qbittorrentvpn#169]
2023-03-05 14:04:05,193 DEBG 'start-script' stderr output:
modprobe: FATAL: Module iptable_mangle not found in directory /lib/modules/5.16.0-0.bpo.4-amd64

**Comment by XenoBIT78** [comment]
nvm..   found solution i log after a restart :)

**Comment by josecrosa** [comment]
Could you explain the solution more. I think I'm running into the same issue.

**Comment by josecrosa** [comment]
This log?


qbittorrentvpn-qbittorrent-1  | 2023-03-29 16:56:13,221 DEBG 'start-script' stdout output:
qbittorrentvpn-qbittorrent-1  | [info] Attempting to load iptable_mangle module...
qbittorrentvpn-qbittorrent-1  | 
qbittorrentvpn-qbittorrent-1  | 2023-03-29 16:56:13,224 DEBG 'start-script' stderr output:
qbittorrentvpn-qbittorrent-1  | modprobe: FATAL: Module iptable_mangle not found in directory /lib/modules/5.15.49-linuxkit
qbittorrentvpn-qbittorrent-1  | 
qbittorrentvpn-qbittorrent-1  | 2023-03-29 16:56:13,226 DEBG 'start-script' stdout output:
qbittorrentvpn-qbittorrent-1  | [warn] Unable to load iptable_mangle module using modprobe, trying insmod...
qbittorrentvpn-qbittorrent-1  | 
qbittorrentvpn-qbittorrent-1  | 2023-03-29 16:56:13,231 DEBG 'start-script' stderr output:
qbittorrentvpn-qbittorrent-1  | insmod: ERROR: could not load module /lib/modules/iptable_mangle.ko: No such file or directory
qbittorrentvpn-qbittorrent-1  | 
qbittorrentvpn-qbittorrent-1  | 2023-03-29 16:56:13,233 DEBG 'start-script' stdout output:
qbittorrentvpn-qbittorrent-1  | [warn] Unable to load iptable_mangle module, you will not be able to connect to the applications Web UI or Privoxy outside of your LAN
qbittorrentvpn-qbittorrent-1  | [info] unRAID/Ubuntu users: Please attempt to load the module by executing the following on your host: '/sbin/modprobe iptable_mangle'
qbittorrentvpn-qbittorrent-1  | [info] Synology users: Please attempt to load the module by executing the following on your host: 'insmod /lib/modules/iptable_mangle.ko'
qbittorrentvpn-qbittorrent-1  | 

Neither command works.

qbittorrentvpn % /sbin/modprobe iptable_mangle
zsh: no such file or directory: /sbin/modprobe
qbittorrentvpn % insmod /lib/modules/iptable_mangle.ko
zsh: command not found: insmod
qbittorrentvpn % 


> look in the log..  solution is writen in the logfile..

**Comment by XenoBIT78** [comment]
thats for linux..  i know jack about MacOS...

**Comment by josecrosa** [comment]
What's weird is this was definitely working last month.

**Comment by XenoBIT78** [comment]
but there must be some way to load kernel modules on MacOS too...    

"lsmod is not available on Mac OS X, but other commands exist that offer similar functionality." They list kextutil, kextstat, kextload, kmodunload

but you need to search for a solution.. can't really help there :)

**Comment by josecrosa** [comment]
For future historians: I got https://github.com/MarkusMcNugen/docker-qBittorrentvpn image to work so... shrug.
