### ISSUE TITLE
Automatically add torrents from:

### ISSUE THREAD

**Issue by mouzzampk2014** [binhex/arch-qbittorrentvpn#17]
Hi, I am not sure what I am doing wrong here I am adding right location and save it but still not working. Any help :)

![4](https://user-images.githubusercontent.com/44548525/56080088-705c2080-5df4-11e9-94f0-65d0af4ca015.JPG)

And when I press Save and go back to Options and Monitored folder location is empty 

![5](https://user-images.githubusercontent.com/44548525/56080103-ae594480-5df4-11e9-915b-fb3d008ba02b.JPG)

Thank you

**Comment by mouzzampk2014** [comment]
Sorry its working now :) I had to press little + :) But is it possible to delete .torrent file once torrent file uploaded (that's how desktop version was working)

Thank you

**Comment by mouzzampk2014** [comment]
Everything working fine :) Thank you

**Comment by acosmichippo** [comment]
thanks for putting this here, helped me out too.
