### ISSUE TITLE
VPN_DEVICE_TYPE not found in 4.5.2-1-02

### ISSUE THREAD

**Issue by GekoCH** [binhex/arch-qbittorrentvpn#173]
When I start the latest verion (4.5.2-1-02)
I get an errot
`VPN_DEVICE_TYPE not found in /config/openvpn/FILE.OVPN`

I tried to set en env variable to VPN_DEVICE_TYPE but still the same error

any suggestions?

**Comment by phptanker** [comment]
Just noticed it on my server too. Watchtower updated the image this morning.

**Comment by GekoCH** [comment]
I reverted back to 4.5.2-1-01 that solved the problem for me

**Comment by bart268** [comment]
Wireguard isn't working on the latest release either "[crit] VPN configuration file /config/wireguard/wg0.conf does not contain port on 'Endpoint' line, showing contents of file before exit...". Reverted back to 4.5.2-1-01 as well.

**Comment by phptanker** [comment]
> I reverted back to 4.5.2-1-01 that solved the problem for me
Same here, although not sure how a qBittorrent update caused this..

**Comment by fgy41** [comment]
Same problem after the new update as well.

>>2023-03-30 09:37:57.436549 [crit] VPN_DEVICE_TYPE not found

**Comment by codewatzen** [comment]
Even with the most recent update that came out about 10 minutes ago, this issue is still occurs for me. I reverted to 4.5.2-1-01 and got mine up and working.

**Comment by binhex** [comment]
This issue is now resolved, please pull down 'latest' tagged image.

**Comment by wiffleman** [comment]
Tried today on 4.5.2-1-03 and had this same issue, reverted back to 4.5.2-1-01 and is working fine again.
Should I try updating to latest again and see if it has any difference..?
