### ISSUE TITLE
Force recheck is not working

### ISSUE THREAD

**Issue by mouzzampk2014** [binhex/arch-qbittorrentvpn#20]
Hi, there is a bug in the webui and if you fix it that would be great.

Compare to deluge and rtorrent, qbittorrent doesn't force recheck the existing media. But I can do force recheck with Windows Client version. I checked with my friend and he said the samething. 

So steps I follow to rectify the issue. Windows client can look for existing media evenly when file and folder is renamed but webui version don't. But when I change the filename and foldername to original then force recheck work.

Is it possible for you to fix that?

Thank you 

![3](https://user-images.githubusercontent.com/44548525/57200438-fd257480-6f83-11e9-9132-b31479abcf1e.JPG)

**Comment by binhex** [comment]
im afraid this is outside of the scope of what i can do, please remember i only package qbittorrent, i am not a qbittorrent developer. please post this as an issue on the qbittorrent github repo here:-

https://github.com/qbittorrent/qBittorrent/issues
