### ISSUE TITLE
Cannot authenticate with default qbittorrent password

### ISSUE THREAD

**Issue by AzShad** [binhex/arch-qbittorrentvpn#208]
Hi All,

I have a docker qbittorentvpn in local and I has the default setting for the password : admin/adminadmin
Today I wanted to coonect on the WebUI but for no reason I can't, It's the wrong password. I tried to delete and reinstall the docker but nothing change, 

Someone Can help me ?

**Comment by Joeltimate** [comment]
I had the same issue earlier today when I updated to the latest build. I was able to log in again after rolling back to version 4.6.0-1-01.

**Comment by ChiefGeekOfficer** [comment]
Same issue here, had to downgrade to login

**Comment by Fribb** [comment]
This also impacts connections like Sonarr/Radarr to connect to qbittorent.

**Comment by ChiefGeekOfficer** [comment]
Indeed. Anything that needs to be able to login to it is unable to, including those apps.

**Comment by binhex** [comment]
This is a change from qbittorrent developers, please keep in mind I simply package what is available,

Having said all that one user has reported successfully getting Auth working with the latest image:- https://forums.unraid.net/index.php?/topic/75539-[Support]-binhex---qBittorrentVPN#entry1329646

**Comment by Fribb** [comment]
While it said that QBittorrent should generate a password and output it in the console, I couldn't find it in any of the logs so here is the solution that worked for me to get this working again:

1. downgrade the container to use the 4.6.0-1-01 version so change the repository to `binhex/arch-qbittorrentvpn:4.6.0-1-01`
2. let the container spin up and connect to the WebUI (the old password should work again
3. go to the options -> Web UI -> Authentication and change the password to whatever you prefer, this can't be default `adminadmin` anymore.
4. save the changes
5. change the Unraid template repository to `binhex/arch-qbittorrentvpn` again and let that start
6. after it is up you can now login with the admin user and the new password
7. you now need to go to your sonarr/radarr instances and change the password on each of those. the test should succeed directly with the new password.

**Comment by binhex** [comment]
> > While it said that QBittorrent should generate a password and output it in the logs, I couldn't find it in any of the logs
> 
> This is something that IS in my control, so i will try and make a bit of time to investigate this.

looks like there is an open issue for this:- https://github.com/qbittorrent/qBittorrent/issues/19984

**Comment by rd720** [comment]
I used this work around. Put an exception for you local IP subnet in the config file. Restart the container. Then you can change your password and remove the 2 lines from the config restart the container again. Should be good with the new password.

`[Preferences]
WebUI\AuthSubnetWhitelist=192.168.1.0/24 #use your local subnet
WebUI\AuthSubnetWhitelistEnabled=true`

**Comment by palakmar** [comment]
I have a truenas core and I installed qbittorrent from plugins.   I cannot login and I cannot locate correct qbittorrent.conf file in order to change the default password or remove authentication from specific ips

**Comment by palakmar** [comment]
> I used this work around. Put an exception for you local IP subnet in the config file. Restart the container. Then you can change your password and remove the 2 lines from the config restart the container again. Should be good with the new password.
> 
> ```
> [Preferences]
> WebUI\AuthSubnetWhitelist=192.168.1.0/24 #use your local subnet
> WebUI\AuthSubnetWhitelistEnabled=true
> ```

I have a truenas core and I installed qbittorrent from plugins. I cannot login and I cannot locate correct qbittorrent.conf file in order to change the default password or remove authentication from specific ips.  Would you be able to help me locate the file?

**Comment by nuqz1** [comment]
For anybody wondering about this, found this on reddit and it worked:
Adding this line under [Preferences], in the config file, works, for setting the default password manually to: adminadmin

WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"

**Comment by Edo-wado** [comment]
> For anybody wondering about this, found this on reddit and it worked: Adding this line under [Preferences], in the config file, works, for setting the default password manually to: adminadmin
> 
> WebUI\Password_PBKDF2="@bytearray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"

This does work but a fresh install also needs the WebUI\User=admin parameter.
So full details for user=admin and password=adminadmin would be:

WebUI\User=admin
WebUI\Password_PBKDF2="@ByteArray(72ycFfm20SU9J1917+v4rg==:rmIGmlb3YZukCUlIghBhnu/8ovMGEqloSqoIlga7Tfh/tm0m7uGgHibe/B/rpn7Bs65+SrVcp1AAtPKm5AoVfw==)"

**Comment by brentbiglin** [comment]
> > For anybody wondering about this, found this on reddit and it worked: Adding this line under [Preferences], in the config file, works, for setting the default password manually to: adminadmin
> > WebUI\Password_PBKDF2="@bytearray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
> 
> This does work but a fresh install also needs the WebUI\User=admin parameter. So full details for user=admin and password=adminadmin would be:
> 
> WebUI\User=admin WebUI\Password_PBKDF2="@bytearray(72ycFfm20SU9J1917+v4rg==:rmIGmlb3YZukCUlIghBhnu/8ovMGEqloSqoIlga7Tfh/tm0m7uGgHibe/B/rpn7Bs65+SrVcp1AAtPKm5AoVfw==)"

Unfortunately this didn't work for me. I'm on Truenas Core working with the qBittorrent plugin. Is there more than one configuration file?

I'm editing the one I found here: /mnt/pool/iocage/jails/qbittorrent/root/var/db/qbittorrent/conf/qBittorrent/config/qBittorrent.conf

**Comment by Dougnuth** [comment]
> > I used this work around. Put an exception for you local IP subnet in the config file. Restart the container. Then you can change your password and remove the 2 lines from the config restart the container again. Should be good with the new password.
> > ```
> > [Preferences]
> > WebUI\AuthSubnetWhitelist=192.168.1.0/24 #use your local subnet
> > WebUI\AuthSubnetWhitelistEnabled=true
> > ```
> 
> I have a truenas core and I installed qbittorrent from plugins. I cannot login and I cannot locate correct qbittorrent.conf file in order to change the default password or remove authentication from specific ips. Would you be able to help me locate the file?

Any updates? I'm having the same problem, and cannot find a working solution...

**Comment by Chrunchy** [comment]
> [Dougnuth](/Dougnuth)

You can find the configuration in a subfolder in the /config folder you mapped.
My /config is mapped to /docker/qbittorrent/

So in my case i go and edit /docker/qbittorrent/qBittorrent/config/qBittorrent.conf and added those two lines with whitelisting.
