### ISSUE TITLE
Wiregaurd

### ISSUE THREAD

**Issue by mouzzampk2014** [binhex/arch-qbittorrentvpn#21]
Hi, is there anyway I can use wiregaurd with qbittorrentvpn? Thank you so much

**Comment by binhex** [comment]
you would need to fork this and then install wireguard as part of the build of the image then configure iptables to allow it through, im afraid i wont be able to help past this point and its no small task to get this working and secure so you might want to consider how much you really want to do this firstly :-)

**Comment by mouzzampk2014** [comment]
Hi, I thought I can just put wiregaurd .conf inside qBittorrebtVPN and all
will work automagically :)

Thank you so much for your help

**Comment by binhex** [comment]
Err no if only it was that simple 😁
