### ISSUE TITLE
Latest update breaks OpenSSL/PIA config

### ISSUE THREAD

**Issue by ArteriusDayne** [binhex/arch-qbittorrentvpn#241]
Rolled back to an older version and it works fine.  Was OpenSSL updated for this release?

>2024-06-03 13:07:40 OpenSSL: error:0688010A:asn1 encoding routines::nested asn1 error:Field=crl, Type=X509_CRL 
>2024-06-03 13:07:40 OpenSSL: error:0488000D:PEM routines::ASN1 lib:

**Comment by ekalp** [comment]
Having the same issue as OP.

**Comment by TorchKat** [comment]
Looks like Open SSL got updated from 3.2.1 to 3.3.0.

> 2024-06-03 17:04:49 library versions: OpenSSL 3.3.0 9 Apr 2024, LZO 2.10

**Comment by binhex** [comment]
ok so the CRL issue is a known problem and i have put in code to deal with it but for some reason (i think perhaps docker image caching) you are not seeing the code fix, so try the following:-

stop the container
go to host command prompt
type 'docker pull binhex/arch-int-vpn:latest'
type 'docker pull binhex/arch-qbittorrentvpn:latest'
exit out of the terminal
start the container and try openvpn again

**Comment by ekalp** [comment]
> ok so the CRL issue is a known problem and i have put in code to deal with it but for some reason (i think perhaps docker image caching) you are not seeing the code fix, so try the following:-
> 
> stop the container go to host command prompt type 'docker pull binhex/arch-int-vpn:latest' type 'docker pull binhex/arch-qbittorrentvpn:latest' exit out of the terminal start the container and try openvpn again

Tried your recommendation and I’m seeing the same issue. Went so far as to nuke the container and images, then rebuild using docker compose and it still errored out.

**Comment by binhex** [comment]
Found the issue and fixed please pull down tagged image 'latest' just built.

**Comment by ekalp** [comment]
> Found the issue and fixed it, please pull down tagged image 'latest' just built.

Thank you! Can confirm it is resolved with the latest image. 🤘
