### ISSUE TITLE
Getting VERY slow speeds (up AND down)

### ISSUE THREAD

**Issue by kpupp** [binhex/arch-qbittorrentvpn#253]
I noticed the other day that my speeds are crawling when they used to sprint. If I'm lucky, they top out around 2MBps (in either direction), and I got REALLY lucky with some tweaks that I got to 4.5MBps yesterday (which I can't get back). Even known good things like Linux torrents are slow as molasses. I'm using PIA, GCM ciphers after reading some other support threads. 

Both DelugeVPN and QbittorrentVPN suffer these slow speeds, but the sticky part is on other machines with the same PIA endpoint, there's no issue with speeds. They often climb into the 10s with the same torrents.

I tried both speedtest and a `curl` download of Ubuntu from within the QbittorrentVPN container and they show speeds consistent with my fiber connection (the Ubuntu download immediately hit 20MBps), so I think something might be wrong with the config or something? I've tried the latest (to get around that socket issue (I WAS using the linuxserver image previously)), and binhex repo image version from just before the socket issue, and none of that has changed anything. I've tried disabling one or the other to see if it helps, and it doesn't seem to.

A few weeks ago I didn't seem to have any issues like this, so I'm not sure what might've happened. The storage devices (network attached) and other settings haven't changed, nor have the ovpn files I'm using (I reverted to the non GCM cipher file to check, and same problem). 

I checked out the VPN FAQ and nothing in there has made a different for Qbittorrent or Deluge, and I also tried Wireguard vs. OVPN and the speeds stayed the same. Is there anything else to try?

Edit: Third time's the charm, maybe. Or maybe some bad trackers - a couple reboots and a reinstall seem to have sorted things out.

**Comment by kpupp** [comment]
Well, actually: tried with another problem torrent, and on a Windows machine with a PIA port-forwarded endpoint I get between 7-10MBps. On a Linux machine with the same PIA endpoint, I only get between 1-2 MBps, if I'm lucky. Maybe something IS going on?

**Comment by binhex** [comment]
I'm running this image myself, i have a symmetrical gigabit fibre connection and whilst i never see gigabit speeds i do see speeds in the range of 20-30 MB/s, for example running right now, this is using PIA with wireguard:-
![image](https://github.com/binhex/arch-qbittorrentvpn/assets/1121837/87b45c40-87b0-442f-a59a-4a9a18fd41a0)

**Comment by kpupp** [comment]
I was definitely getting differences with Windows+PIA vs. the container for more than one torrent, but many do seem to finish rather quickly. Maybe the trackers were bad/blocking something or some such. I'll have to do some more tinkering around, but maybe it was just bad luck or an off day. Thanks for double checking.

**Comment by kpupp** [comment]
For what it might be worth @binhex, here's what I mean. The dark version is the container/Linux, the light version is Windows. Same endpoint, cipher, protocol, etc. I waited for them both to roughly max out before grabbing the screenshot.

![image](https://github.com/binhex/arch-qbittorrentvpn/assets/105092694/a81b3feb-caee-4096-87d9-bc5c5be7c19a)

**Comment by binhex** [comment]
did you see Q3, this made a big difference for me:- https://github.com/binhex/documentation/blob/master/docker/faq/qbittorrentvpn.md

**Comment by kpupp** [comment]
I did - that hasn't made a difference for me.

**Comment by binhex** [comment]
it might be related to I/O, i dont know if you are an unraid user or not, if so try writing to cache drive, if you are not an unraid user then try pointing the bind mount at fast storage, such as NVMe or SSD.

**Comment by binhex** [comment]
i assume you have seen Q6 as well right? https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md

**Comment by kpupp** [comment]
I have, will try all of this (again/double check settings and such) and do
some more digging.

**Comment by kpupp** [comment]
So I did some talking with PIA today (and a little tinkering, AND Ubuntu had an update) and it _seems_ like things might be a little better. They had me do some debug logging on my windows machine and found some issues with OpenVPN even there, and Wireguard did better even on Windows. I swapped to that - again - on the Linux machine and it seemed less rubberbandy, though it's still there a bit (both Deluge and Qbit). Ubuntu had an update which included a ton of network items, so maybe something was up there too. I'll keep an eye on things over the next while and update if things get funky again.

**Comment by kpupp** [comment]
Out of curiosity @binhex, are you also using PIA? I've still been having connection and speed issues lately, even after implementing their/your ideas for fixes. Seems a lot of people are having issues lately with PIA and quality, so wanted to ask.

**Comment by kpupp** [comment]
Back to having issues today. :(

**Comment by kpupp** [comment]
It seems like, for what it's worth, I get much better speeds after 1) restarting the container after 2) its had a port assigned for a while. Does the script do something like that when the port changes? Although, I also thought that PIA port leases lasted about 60 days, so I wonder why it changes so much with this container?

**Comment by kpupp** [comment]
I can indeed (usually) reliably replicate the fact that restarting the container after a while almost always results in better connections, speed, performance, the whole shebang. Down and up. Is there a reason that might be?
