### ISSUE TITLE
qBitTorrent can't start because... I don't know

### ISSUE THREAD

**Issue by UntouchedWagons** [binhex/arch-qbittorrentvpn#29]
I'm trying to incorporate arch-qbittorrentvpn into a docker stack along with some other services and qbittorrent is being troublesome

Container log: https://paste.dimdev.org/igamejalub.pl
Relevant info from docker-compose.yaml

    qbittorrent:
      image: binhex/arch-qbittorrentvpn
      container_name: qbittorrent
      restart: unless-stopped
      privileged: true
      volumes:
        - /etc/localtime:/etc/localtime
        - /mnt/data:/mnt/data
        - ./appdata/qbittorrent:/config
      ports:
        - 8118:8118
      cap_add:
        - NET_ADMIN
      environment:
        - VPN_ENABLED=yes
        - VPN_USER=obviouslynotmyrealusername
        - VPN_PASS=obviouslynotmyrealpassword
        - VPN_PROV=airvpn
        - ENABLE_PRIVOXY=yes
        - LAN_NETWORK=192.168.0.0/24
        - NAME_SERVERS=208.67.222.222
        - WEBUI_PORT=8080
        - UMASK=500
        - PUID=500
        - PGID=500

For some reason, ./appdata/qbittorrent/qBittorrent has a folder mask of 0377 which probably has a role in this issue.

**Comment by UntouchedWagons** [comment]
I just realized that UMASK is supposed to be file permissions. I changed it to 000 as the original example and qbittorrent can start. But I can't connect to its web UI even if I map port 8080 to the host.

**Comment by binhex** [comment]
you will need to either chmod all your files/folder in /config or delete everything in /config and restart the container, as the stuff up with the umask will still be present with any files created.

**Comment by UntouchedWagons** [comment]
I stopped the container, ran `sudo chown -R media:media qbittorrent/` and changed PUID and PGID to 500 and now it can start. I don't know why it couldn't start when I tried that earlier. Oh well at least it works. Thanks
