### ISSUE TITLE
Cant access webinterface when restarting docker container

### ISSUE THREAD

**Issue by ressof** [binhex/arch-qbittorrentvpn#31]
When I restart qbittorrentvpn with docker-compose I cant access the webinterface.
It seems that it having problem with this command:
/root/getdns.sh "www.google.com"
and I must reboot my server to get it to work again or restart docker service.
I'm using TigerVPN as service provider.

**Comment by usman-umer** [comment]
I just fixed this by deleting the /data folder in the config, then restarted the docker. Personal configs are still intact.

**Comment by binhex** [comment]
related issue https://github.com/binhex/arch-delugevpn/issues/181

**Comment by usman-umer** [comment]
Thank you, everything works great now! This saved me from running my through my VPN tunnel, which is obviously not ideal.
