### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by giejay** [binhex/arch-qbittorrentvpn#35]
I would love for this docker image to work on my Raspberry Pi, tried to build it myself but it seems really tied to ArchLinux of which I can't find an ISO. You know how to make it compatible with ARM?

**Comment by idolize** [comment]
Perhaps using https://github.com/dockcross/dockcross would be helpful for maintaining an ARM build? @binhex

**Comment by AWDDude** [comment]
I too would like an arm port.

**Comment by glowacki-dev** [comment]
For anyone still looking to run this container on raspberrpy pi I've managed to get it running with just a few changes (mostly commenting out stuff that doesn't work, but doesn't seem required for this specific app):
- https://github.com/glowacki-dev/arch-base-aarch64/tree/rpi - that's the base os image. Build it and tag as `arch-base`
- https://github.com/glowacki-dev/arch-int-vpn/tree/rpi - this one uses the one above and extends it with openvpn. Again, build it and tag as `arch-int-vpn`
- https://github.com/glowacki-dev/arch-qbittorrentvpn/tree/rpi - this is the final image that adds qbittorrent. Build it and run this one according to the documentation.
I've only tested this setup with openvpn providers, and the performance on raspberrypi was quite bad (cpu bound most of the time and thus never getting speeds above to 1-1.5MB/s)

**Comment by binhex** [comment]
@glowacki-dev i appreciate the effort put into this, when i get a spare minute i will take a look at your code changes.

**Comment by space192** [comment]
any update on the arm64 port?

**Comment by ShrirajHegde** [comment]
I have an update regarding this

I have added support for multiplatform builds on the base image (https://github.com/binhex/arch-qbittorrentvpn/pull/200). This also required multiplatform images of https://github.com/binhex/arch-base (https://github.com/binhex/arch-base/pull/4).

The built image is here:
https://hub.docker.com/r/shrirajhegde/binhex-arch-qbittorrentvpn/tags

With the way, https://github.com/binhex/arch-base/pull/4 works, @glowacki-dev's work on RPi support can be integrated relatively easily by adding armhf directory to both the repositories (the intermediate image https://github.com/binhex/arch-int-vpn requires no modification).

**Comment by ShrirajHegde** [comment]
@binhex Can you please take a look at pull requests https://github.com/binhex/arch-base/pull/4 and https://github.com/binhex/arch-qbittorrentvpn/pull/200 ?

Especially, merging https://github.com/binhex/arch-base/pull/4 will add ARM64 support to a lot of other docker projects using it as a base.

**Comment by binhex** [comment]
Hi yes I did spot the pr I just have not had time yet to have a good look at it maybe I will get some time this weekend

**Comment by binhex** [comment]
OK it's been a long time coming, but it's here, the latest image now includes arm64 support, please pull it down and let me know how you get on.

@ShrirajHegde  Thanks for the incentive to get this done, i did rework your PR a LOT in the end as i wanted to try and DRY the code out, quite pleased with the end result though.

**Comment by MatzHilven** [comment]
I'm getting the following error when starting up the container: `exec /usr/bin/dumb-init: exec format error`, a quick google said `this means that you have wrong architecture of your image`.

Using the following compose file:

`version: '3'

services:
  qbittorrentvpn:
    platform: linux/amd64
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrentvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - proxy
    volumes:
      - ./data/config/:/config
      - /mnt/data/:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VPN_ENABLED=no
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=8.8.8.8,8.8.4.4
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=5678
      - DEBUG=false
      - WEBUI_PORT=8080
      - UMASK=000
      - PUID=0
      - PGID=0
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
      - "8118:8118"
    labels:
      ... some traefik stuff

networks:
  proxy:
    external: true`
