### ISSUE TITLE
X Window System interface alongside WebUI?

### ISSUE THREAD

**Issue by RainOne** [binhex/arch-qbittorrentvpn#36]
Would there be any chance of adding a X11/Graphical interface through VNC to the qBittorrent client alongside the Web Interface? There's a lot of automation/mass settings available on the regular qBitTorrent interface (mostly RSS feeds monitoring and editing, but also mass category specific ratio settings) not available in the default WebUI (some alternative WebUIs provide that information, but they're cubersome and not as straight forward as the regular WebUI interface nor the original graphicl interface).

**Comment by binhex** [comment]
> Would there be any chance of adding a X11/Graphical interface through VNC to the qBittorrent client alongside the Web Interface?

im afraid this wont happen, this would add WAY too much bloat to the image.
