### ISSUE TITLE
UDP VPN Connections not supported

### ISSUE THREAD

**Issue by mtalexan** [binhex/arch-qbittorrentvpn#40]
VPN connections can be TCP or UDP, and most VPN providers recommend UDP unless you have a specific need for TCP.   In particular the providers that specifically allow P2P traffic usually recommend UDP for the VPN connections.

Testing this case, it appears it might be possible for a UDP VPN to work if:
* [ ] parsing of the ovpn file allows `proto udp` in addition to `proto tcp-client` (currently works, but needs to be guarantee)
* [ ] iptables need to allow udp port 1194 instead of tcp 443

**Comment by binhex** [comment]
udp and tcp are both supported and the ovpn file is parsed, i myself use udp connection to PIA endpiint, what makes you think it isnt supported? supervisord.log file please.

**Comment by mtalexan** [comment]
You're correct, my mistake.  In reproducing the problem I found it's actually caused by #41.  My OVPN file has a block like this:
```
remote 185.159.158.133 80
remote 185.159.158.133 443
remote 185.159.158.133 4569
remote 185.159.158.133 1194
remote 185.159.158.133 5060
remote 185.159.158.137 80
remote 185.159.158.137 443
remote 185.159.158.137 4569
remote 185.159.158.137 1194
remote 185.159.158.137 5060
remote 185.159.158.141 80
remote 185.159.158.141 443
remote 185.159.158.141 4569
remote 185.159.158.141 1194
remote 185.159.158.141 5060
remote 185.159.158.142 80
remote 185.159.158.142 443
remote 185.159.158.142 4569
remote 185.159.158.142 1194
remote 185.159.158.142 5060
server-poll-timeout 20
``` 
And only the first line is getting parsed, so only port 80 is getting opened in the iptables rather than all of the ports listed.
