### ISSUE TITLE
VPN profile configuration issues

### ISSUE THREAD

**Issue by Ammar7347** [binhex/arch-qbittorrentvpn#43]
The docker image supports pia, airvpn and custom profiles. I don't have airvpn or pia so I tried configuring it with the custom .ovpn profile. I keep getting errors.

![image](https://user-images.githubusercontent.com/19525838/82720461-4189cc80-9ccd-11ea-873d-b7292db7fccd.png)

I tried my own server's .ovpn profile and a 3rd party provider's profile. Any help would be highly appreciated.

**Comment by shawncatz** [comment]
This is caused by the openvpn files getting permissions changed by `chmod` in the `install.sh` script: https://github.com/binhex/arch-qbittorrentvpn/blob/master/build/root/install.sh#L84

I haven't figured out the right way to deal with this yet
