### ISSUE TITLE
/config/qBittorrent/downloads is not an intuitive downloads directory

### ISSUE THREAD

**Issue by dylanmtaylor** [binhex/arch-qbittorrentvpn#49]
It would make more sense to have downloads stored to /downloads, bind-mounted in separately from the configuration files. This can be confusing for users.

**Comment by downey-lv** [comment]
I agree it doesn't really make sense, especially when passing the downloads to something like radarr, we're not gonna map a directory that's inside another docker's config directory. 
The docker hub page shows adding a /data mount, then shouldn't that be the default download directory?

**Comment by gdreelin** [comment]
Any new word on this? Is there a way to direct the downloads to a directory of my choice?

**Comment by downey-lv** [comment]
Although changing the default directory for the docker would make sense, the download directory can just easily be changed in qBittorrent GUI settings (Default Save Path), so this issue should be just closed

**Comment by gdreelin** [comment]
Yeah I figured that out after tinkering with it a while

**Comment by Vendo232** [comment]
I need to store downloads in root /media/500/downloads folder. How should I set this up?

![image](https://user-images.githubusercontent.com/44098230/170576034-966a30b0-e723-494c-b8f1-9952bc21684a.png)

**Comment by Vendo232** [comment]
> Yeah I figured that out after tinkering with it a while

would you be so kind and share how you setup path to independent download folder?

**Comment by Vendo232** [comment]
trying to mount DATA folder to Downloads, will see if it works

![image](https://user-images.githubusercontent.com/44098230/170579123-f4ef3d7d-af92-4116-884e-7b465a5f90c9.png)

**Comment by Vendo232** [comment]
I mapped /data to /media/500/downloads in compose but sonarr is giving me error because it adds the /data element to it

2022-05-26 15:40:36.8|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /data/The.Simpsons.S33E21.480p.x264-mSD[eztv.re].mkv. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder

**Comment by Vendo232** [comment]
took me 2 hrs to figure this out, please consider updating your README

Compose
![image](https://user-images.githubusercontent.com/44098230/170588970-9e26acf6-89fe-4233-bbae-05ba13fef427.png)

Settings:
![image](https://user-images.githubusercontent.com/44098230/170589005-805930f0-86cf-400f-9504-7ccea220dd9e.png)

path and mounted folder apparently must match for Sonarr to enable COPYING process.

also users should make sure they use UMASK 000 for both Sonarr docker and QBittorrent
