### ISSUE TITLE
/usr/bin/qbittorrent-nox: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xXx-st4cktr4c3-xXx** [binhex/arch-qbittorrentvpn#5]
Seems a few people are experiencing this, but there is a simple fix if you can include it in the image:
```
pacman -S binutils
strip --remove-section=.note.ABI-tag /usr/lib64/libQt5Core.so.5
```
That fixes it for me everytime for me when you push a new image update so it should help others with their issue.

Thanks!

**Comment by binhex** [comment]
Excellent!, i appreciate this post, i got a few questions for you first though before i include it:-

1. firstly how did you come across this as a fix?, Qt guru? :-)
2. the fix you have detailed, can you tell me what it actually is doing, what is the .note.ABI-tag?
3. are there any side effects to performing the removal of  .note.ABI-tag from the library?

**Comment by xXx-st4cktr4c3-xXx** [comment]
1. It has been floating around on some bug repos and forums: https://bugs.archlinux.org/task/61130 https://github.com/Microsoft/WSL/issues/3023
2. It looks like the ABI tag exists, it can't be directly linked by other shared objects and only executed by the ld-linker (probably the gold-linker as well).
3. I have been doing this fix for a month now with no side effects. Everything runs as normal.

**Comment by binhex** [comment]
thanks for the replies, ok sounds good, i will build it with the fix in place locally, test it hasnt broken anything on my currently working system (doesnt require this fix), if it all passes then i will commit and build.

i can replicate the issue on a mac laptop running 10.14.2, and with the fix in place it does indeed allow qbittorrent to start, so it looks good as far as fixing it for systems that have the issue, nice!.

**Comment by binhex** [comment]
image now built and it fixes the issue for the mac, so im assuming it will also fix the issue for other hosts, please pull down the image and give it a try, if it looks good i will close off this issue.

referencing other issues relating to this: #3 and #4

**Comment by guillaumedsde** [comment]
watchtower just pulled the latest image, it didnt break anything for me :)

**Comment by binhex** [comment]
Excellent, I'm closing off.
