### ISSUE TITLE
Not getting a port from PIA

### ISSUE THREAD

**Issue by downey-lv** [binhex/arch-qbittorrentvpn#50]
Hi,

Looks like there are issues getting port from PIA. They've changed the endpoint address, so the script doesn't recognize it, but there seem to be more issues. I found that there has been a post regarding port forwarding on Aug 25th with a script that should be run to get ports forwarded. 
https://www.privateinternetaccess.com/helpdesk/kb/articles/can-i-use-port-forwarding-without-using-the-pia-client-current-gen-only

```
[info] Port forwarding is enabled,
[info] Checking endpoint 'de-berlin.privacy.network' is port forward enabled...,
[warn] PIA endpoint 'de-berlin.privacy.network' is not in the list of endpoints that support port forwarding, DL/UL speeds maybe slow,
[info] Please consider switching to one of the endpoints shown below,
[info] List of PIA endpoints that support port forwarding:-,
...
[info] de-berlin.privateinternetaccess.com,
...
[info] Attempting to get dynamically assigned port...,
[warn] Exit code '7' from curl != 0 or no response body received
```

**Comment by ljmerza** [comment]
the script is the same. You can see [here](https://github.com/binhex/arch-int-openvpn/blob/master/run/root/getvpnport.sh) the url to get a port is the same as the script provided. It looks like all port forwarding is down for PIA

**Comment by binhex** [comment]
https://github.com/binhex/arch-delugevpn/issues/194#issuecomment-691044876

**Comment by blake1029384756** [comment]
@binhex Hereis a git repo with a script to request a port from PIA's Nextgen servers. https://github.com/fm407/PIA-NextGen-PortForwarding

**Comment by binhex** [comment]
@blake1029384756 that script makes use of some config files from official pia app and thus is fragile at best, im afraid im not going to implement this as i feel it will break sooner rather than later, im awaiting official native wireguard support from pia.

**Comment by ljmerza** [comment]
a temp fix is better than broken software for an undetermined period of time.

**Comment by downey-lv** [comment]
They've added information regarding the next gen forwarding today: https://www.privateinternetaccess.com/helpdesk/kb/articles/next-generation-port-forwarding

**Comment by binhex** [comment]
> They've added information regarding the next gen forwarding today:

thank god!, right i will take a look.

**Comment by rangulicon** [comment]
> > They've added information regarding the next gen forwarding today:
> 
> thank god!, right i will take a look.

I came here to mention the official scripts for the PIA NextGen servers, but it looks like you are already looking at them. Thank you for all your efforts.

**Comment by binhex** [comment]
Support for multi remote endpoints and PIA 'Next-Gen' networks now complete, see Q19 and Q20 for details:-
https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
