### ISSUE TITLE
Latest commit breaks ports with less than 4 digits

### ISSUE THREAD

**Issue by rg9400** [binhex/arch-qbittorrentvpn#52]
My container stopped working after updating to commit b7ce500cb84539ed6cf0b6a81e88df72eb75f118. Everything worked perfectly before then.

From what I can discern, the issue is that my ovpn is using a port with only 3 digits (995), and the latest commit is not picking up ports that are not 4 or 5 digits.

**Comment by binhex** [comment]
https://github.com/binhex/arch-delugevpn/issues/202

**Comment by binhex** [comment]
resolved
