### ISSUE TITLE
curl failure for https://serverlist.piaservers.net/vpninfo/servers/v4

### ISSUE THREAD

**Issue by Dubwize** [binhex/arch-qbittorrentvpn#53]
The Container fails to start with error.
"PIA VPN server info JSON cannot be downloaded from URL 'https://serverlist.piaservers.net/vpninfo/servers/v4' exit code from curl is '0'"

This looks to have just happened today sometime as I know it was connected and torrenting last night.
Latest pull from the docker hub.

Log with debug on.
`2020-10-11 13:13:06.633926 [info] Permissions already set for volume mappings
2020-10-11 13:13:06.672621 [info] Deleting files in /tmp (non recursive)...
2020-10-11 13:13:06.713619 [info] VPN_ENABLED defined as 'yes'
2020-10-11 13:13:06.747786 [info] VPN_CLIENT defined as 'openvpn'
2020-10-11 13:13:06.782836 [info] VPN_PROV defined as 'pia'
2020-10-11 13:15:07.916591 [crit] PIA VPN server info JSON cannot be downloaded from URL 'https://serverlist.piaservers.net/vpninfo/servers/v4' exit code from curl is '0', exiting...`

I can hit the page from local browser.
![image](https://user-images.githubusercontent.com/16105140/95685185-54416700-0bc4-11eb-89d8-8ffdf89f2668.png)

nslookup & ping from within the container function fine.
![image](https://user-images.githubusercontent.com/16105140/95685211-8357d880-0bc4-11eb-8b0b-5e84722b744c.png)
![image](https://user-images.githubusercontent.com/16105140/95685224-95d21200-0bc4-11eb-8c09-eb69f329fd00.png)

Curl from within the container
![image](https://user-images.githubusercontent.com/16105140/95685327-2f012880-0bc5-11eb-8c6a-97bec700cd3b.png)

and same from outside.
![image](https://user-images.githubusercontent.com/16105140/95685393-9f0fae80-0bc5-11eb-96ee-8405e82949b8.png)

**Comment by Dubwize** [comment]
It looks like a PIA thing, since the curl fails outside the container, but figured I would let you know. Maybe we can bypass the polling of the server list for now, since the container will not start at all with it in.

Thanks

**Comment by binhex** [comment]
yes, sadly serverlist is a requirement for wireguard and is also used to assign an incoming port (for both wireguard and openvpn), if you cannot download the json from 'https://serverlist.piaservers.net/vpninfo/servers/v4' then you cannot proceed.

the only exception to this is if you are using openvpn and you do not require port forwarding (STRICT_PORT_FORWARD set to no), or of course you arent a pia user.

**Comment by Dubwize** [comment]
Unfortunately even when running as OpenVPN, with port forwarding off, the container will still not start.
![image](https://user-images.githubusercontent.com/16105140/95749112-15192180-0c69-11eb-913c-fc048eb70baf.png)
![image](https://user-images.githubusercontent.com/16105140/95749268-527daf00-0c69-11eb-9042-863c0e977336.png)

**Comment by Dubwize** [comment]
Further troubleshooting shows this issue is totally me.  Seems my firewall can curl that URL without issue, but the systems behind it can't.

I also noticed your change to make the requirement for the curl less restrictive.  I'll give that a try when I get a minute.

Thank you
