### ISSUE TITLE
Latest tag is from incorrect qBT release

### ISSUE THREAD

**Issue by apetresc** [binhex/arch-qbittorrentvpn#55]
I just updated to the recently-pushed `:4.3.0-1-02` tag, but as far as I can tell, it's still running 4.2.5. The About dialog seems to think so, at least.

**Comment by vtruong68** [comment]
I'm using the latest tag as well and am also seeing v4.2.5 in the Web UI under "About".

**Comment by apetresc** [comment]
Ah, it looks like the newest tag, `:4.3.0-1-03` has resolved it, I see the latest version now 😃 Thanks!
