### ISSUE TITLE
Why is the default download folder  /config/qBittorrent/downloads   ???

### ISSUE THREAD

**Issue by minidarknova** [binhex/arch-qbittorrentvpn#56]
Why please?

**Comment by r0arkin** [comment]
Wow. Someone woke up on the wrong side of the bed today. You can either set the default download directory via the WebUI or via /config/qBittorrent.conf

**Comment by binhex** [comment]
Because it has to be set to something known, and thus qBittorrent developers (that is NOT me by the way!) decided to set it to a sub folder of the configuration path, which in the case of this docker image is ```/config/qBittorrent/downloads/```. As @r0arkin rightly suggests, this can be changed to whatever you want via config file or web ui.

**Comment by ljmerza** [comment]
is there a way to set the qbittorrent version used?

**Comment by r0arkin** [comment]
> is there a way to set the qbittorrent version used? This seems to always default to the latest version but many trackers dont approve the latest version until later on so you get stuck.

Are you using Docker?

**Comment by ljmerza** [comment]
> > is there a way to set the qbittorrent version used? This seems to always default to the latest version but many trackers dont approve the latest version until later on so you get stuck.
> 
> Are you using Docker?

yes

**Comment by binhex** [comment]
@ljmerza that is a bit rude to crash another persons issue with something completely unrelated!, i see you then created an issue and closed it, so at least you realised it wasnt the done thing i guess.

**Comment by ljmerza** [comment]
yeah it'll be okay. this issue needs to be closed anyways
