### ISSUE TITLE
With strict port forwarding, possible to also allow a UDP port in `ADDITIONAL_PORTS`?

### ISSUE THREAD

**Issue by anirbanmu** [binhex/arch-qbittorrentvpn#70]
I see that if I specify a port in `ADDITIONAL_PORTS`, it is added to the iptables rules to allow tcp. Is there any way to additionally also allow udp?

**Comment by binhex** [comment]
ADDITIONAL_PORTS is **not** used for a incoming port, it is used to specify incoming ports for other applications when sharing the docker network with multiple containers.

**Comment by anirbanmu** [comment]
Sorry, my terminology is probably bad. That is what I meant. I have another (not this repo) container that is using the network of this container (this repo). The other container would like some UDP ports exposed to the local network (incoming from local network).

Apologies for the bad terminology.

**Comment by binhex** [comment]
ok i see, thats fine i have created a 'test' tagged image with the change to allow both udp and tcp for ADDITIONAL_PORTS that are defined, please can you pull it down and see if this fixes your issue.

**Comment by anirbanmu** [comment]
thanks, i might not be able to try it immediately here but i will hopefully soon-ish & then let you know!

**Comment by anirbanmu** [comment]
I ended up not needing this functionality; will reach out if I end up having a need for it in the future. Thank you much for trying to help so quickly! Much appreciated.
