### ISSUE TITLE
 Unable to pass other docker through qbittorrentvpn #8 

### ISSUE THREAD

**Issue by SeNeO** [binhex/arch-qbittorrentvpn#8]
I'm trying to connect other docker network through this one using `--network "container:binhex-qbittorrentvpn"`.
The other docker starts fine and I can see in their logs there seems to be working fine, but I can't connect to their webui.
The issue is probably with the default config for the network (iptables?) not allowing connection to the port for the webui for the other docker, (ex: port 9117 for jackett).
Is there anyway to achieve what I want?
I'm running the docker on an Unraid machine, and trying to route at least jackett/sonnar/radarr through this docker.

**Comment by binhex** [comment]
you cant do this, sorry, for obvious reasons iptables is VERY tied down in this image, and thus it will block traffic for other applications, feel free to fork and have a play, but watch out for ip leakage if you do this.

**Comment by SeNeO** [comment]
Thanks for your answer, that's what I was fearing. I will use this one as a proxy instead.
