### ISSUE TITLE
FATAL: kernel too old

### ISSUE THREAD

**Issue by deepfriedmind** [binhex/arch-qbittorrentvpn#81]
I just tried version `4.3.3-1-04` of the container and now it doesn't boot and the log only says `FATAL: kernel too old`. I'm on a Synology DS916+ running DSM 6.2.3-25426 Update 3, which has Linux kernel 3.10.105. I downgraded to `4.3.3-1-03` with the same result, then to `4.3.3-1-02` which works as previously. I'm using OpenVPN, not Wireguard, so kernel age should not be an issue.

**Comment by hot22shot** [comment]
Same issue here, I'm also with a DS916+ but on the beta DSM 7.0-41222.
By the way my kernel version is 'Linux DSM 3.10.108' you would thought that Synology would have bumped that to something more recent with the release of DSM 7.

**Comment by binhex** [comment]
duplicate:- https://github.com/binhex/arch-delugevpn/issues/256#issuecomment-789015393

**Comment by deepfriedmind** [comment]
I searched the issues in this repo and didn't find anything. I didn't realize it was mentioned in another repo.

So that's it, something changed in `4.3.3-1-03` and now people with these devices can never update the image again?

**Comment by binhex** [comment]
please post in the other thread.
