### ISSUE TITLE
 Schedule the use of alternative rate limits not working

### ISSUE THREAD

**Issue by mnyce** [binhex/arch-qbittorrentvpn#83]
Hey All,

Thanks to binhex for this excellent container.

When enabling "Schedule the use of alternative rate limits" in the webui (4.3.3-1-06), the rate limits never actually change.

Happy to provide any logs that I can.

**Comment by binhex** [comment]
please post all qbittorrent issues on the qbittorrent github repo, this issue is not related to the packaging as a docker image:- https://github.com/qbittorrent/qBittorrent/issues/new
