### ISSUE TITLE
DHT port should probably be 8999 instead of 6881 and maybe optional

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-qbittorrentvpn#9]
According to https://github.com/qbittorrent/qBittorrent/issues/3089 from a number of years ago, the port for DHT changed. And I think most don't need DHT on their local network, so it might be worth suggesting it be optional.

**Comment by binhex** [comment]
6881 is actually for use as a incoming port and DHT when the vpn is NOT enabled, so it is an optional port, i could make that clearer in the readme, obviously when the tunnel is running everything goes over that, with DHT using the dynamically (for pia at least) allocated incoming port.

**Comment by fryfrog** [comment]
Are you forcing qB to use 6881? It still seems like that should be 8999 and another (not as good) qB + vpn docker image uses that port instead of 6881.

https://github.com/MarkusMcNugen/docker-qBittorrentvpn

I'm still not actually *using* it, so all this is passive consumption of docs and issues and Google searching.

**Comment by binhex** [comment]
> Are you forcing qB to use 6881?

nope, i got no problems switching it to 8999 to be fair, as its not really used unless the vpn is off and as thats really the main point of this image most people wont actually be using it either, so switching it should be fairly painless.

im well aware of the other docker image btw :-), and yeah its not as good as mine lol.

**Comment by fryfrog** [comment]
To be clear, I'm not even sure if switching is right. In the webui, I could not find anywhere you can change the DHT or anything that has 6881 *or* 8999.

**Comment by binhex** [comment]
> To be clear, I'm not even sure if switching is right. In the webui, I could not find anywhere you can change the DHT or anything that has 6881 _or_ 8999.

i would suspect the reason you find no reference to dht port is because it most probably uses the incoming port, rtorrent does the same and is quite happy to use the same port for incoming peer connections and dht (although rtorrent allows you to have separate ports for both).

**Comment by binhex** [comment]
fyi i dont do any clever stuff to configure qbittorrent to use port 6881 when the vpn is off, its completely up to the user to configure the incoming port, so in reality they can set it to whatever they want, as long as they have defined it as such for the container.

**Comment by fryfrog** [comment]
From my logs:
```
[warn] INCOMMING_PORT not defined (via -e INCOMMING_PORT), defaulting to '8999'
```

So it looks like even you knew it defaults to port 8999.

**Comment by binhex** [comment]
> [warn] INCOMMING_PORT not defined (via -e INCOMMING_PORT), defaulting to '8999'

i dont have that in my code:-

https://github.com/binhex/arch-qbittorrentvpn/search?q=8999&unscoped_q=8999&type=Code

i also dont have an env var called "INCOMING_PORT", now i am confused!, looks like my logging format.

**Comment by fryfrog** [comment]
Ha, bah this is me. From many ago when I tried to use your arch- stuff to make it. Sorry!

It was from `2018-09-20` :)

Anyway, I do think this means your documentation should s/6881/8999 and maybe make it clear what each port is for, the webui port should be all 80% of people need forwarded.

**Comment by binhex** [comment]
lol you had me there i thought i was going mad!

**Comment by binhex** [comment]
ok so you are suggesting keep 6881 for incoming port for peer connections (only used when vpn is off of course), and add an additional port of 8999 for incoming dht (again only used when vpn is off), correct?

**Comment by fryfrog** [comment]
I can't find anything that supports either way. :/

Incoming port is 8999/tcp https://github.com/qbittorrent/qBittorrent/search?q=8999

But also 6881/tcp https://github.com/qbittorrent/qBittorrent/search?q=6881

Let me see if I can find a support channel to ask.

**Comment by binhex** [comment]
@fryfrog i think for now im going to close this issue, it really is a minor issue (if an issue at all), at the end of the day users can choose whatever incoming port they want on the host side or even the container side (no auto configure of the incoming port when vpn disabled), if im missing something then please pipe up and i will re-open

**Comment by fryfrog** [comment]
I'll just submit a pull request when I figure out what is correct wrt ports. :)
