### ISSUE TITLE
Wireguard PIA Stalled Downloads

### ISSUE THREAD

**Issue by loganmrocha** [binhex/arch-qbittorrentvpn#90]
[supervisord.log](https://pastebin.com/qDKTkynk)
After perusing the supervisord.log file I did not see any glaring issues with my setup, but I'm eager to figure out where I'm going wrong. I have tried different endpoints for Wireguard PIA, but they have not improved my speed. 

The logs show that I am able to be reached and the Web GUI shows small amounts being downloaded, but all torrents stay at 0.0% and 0 pieces. It seems like the scripts are successfully taking care of port forwarding and the web GUI reflects an updated port, but no luck.

I'm fighting off the urge to scrap Wireguard for OVPN, but I've never had an issue while running my own Wireguard server so I would like to salvage this wreck if possible. 

Thanks for the neat container and helpful debugging logs. 

Here's hoping to a full bit flow recovery!

**Comment by binhex** [comment]
yep i agree the log looks fine, no issues reported, so i suspect the issue is configuration of qbittorrent, can you paste a screenshot of qbittorrent web ui/options/downloads tab, also can you paste your docker run command minus any credentials.
