### ISSUE TITLE
WebUI is broken

### ISSUE THREAD

**Issue by Fischy667** [binhex/arch-qbittorrentvpn#93]
Bittorrent v4.3.4 has a problem with the WebUI.

https://github.com/qbittorrent/qBittorrent/issues/14599

Please update it to at least 4.3.4.1

Latest version is 4.3.5.

**Comment by guitaristtom** [comment]
I noticed this as well.

**Comment by raspberrycoulis** [comment]
Same here. I tested on 4.3.4-1-01 (on Synology NAS) and the web UI was still broken, so have reverted back to 4.3.3-1-07 which is working again.

**Comment by binhex** [comment]
4.3.5 will be built in the next hour, please check for new image then.

**Comment by raspberrycoulis** [comment]
I've tested both `latest` and `4.3.5-1-03` but still broken...

**Comment by binhex** [comment]
sorry guys, got a caching issue with the mirrors, im trying to force it through.....

**Comment by Fischy667** [comment]
Check with ip:port/api/v2/app/version if realy 4.3.5 was built. I'm still getzing 4.3.4

**Comment by raspberrycoulis** [comment]
> Check with ip:port/api/v2/app/version if realy 4.3.5 was built. I'm still getting 4.3.4

Yeah, same with both tags. Shows 4.3.4. It's working on `4.3..3-1-07` so I'll update once this has been fixed.

**Comment by binhex** [comment]
ok please pull down latest now, working for me.

**Comment by raspberrycoulis** [comment]
Hurrah! Yep, all working for me now too. Showing `4.3.5`. Nice work!

**Comment by Fischy667** [comment]
Thanks for the fast fix.
