### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

### ISSUE THREAD

**Issue by BrodyStone21** [binhex/arch-qbittorrentvpn#96]
Currently getting the following error; `The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested`

I did try running the container with `--platform=linux/arm/v7` as well but then I got the following error; `Error response from daemon: image with reference binhex/arch-qbittorrentvpn was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64.`

I am using a Raspberry Pi 4, is this device not compatible with this? Is there a work around? You can find my container below.

`docker run -d     --cap-add=NET_ADMIN     -p 6881:6881     -p 6881:6881/udp     -p 8080:8080     -p 8118:8118     --name=qbittorrent-openvpn     -v /mnt/usb/WD_Black:/data     -v ~/.config/qbittorrent-openvpn:/config     -v /etc/localtime:/etc/localtime:ro     -e VPN_ENABLED=yes     -e VPN_USER=2TNHxkLvKY     -e VPN_PASS=Cd398gRF7g     -e VPN_PROV=custom     -e VPN_CLIENT=openvpn     -e STRICT_PORT_FORWARD=no     -e ENABLE_PRIVOXY=no     -e LAN_NETWORK=192.168.1.0/24     -e NAME_SERVERS=8.8.8.8     -e DEBUG=true     -e WEBUI_PORT=8080     -e UMASK=666     -e PUID=1000     -e PGID=1000     binhex/arch-qbittorrentvpn`

**Comment by Facinorous-420** [comment]
Check this out #35 
Maybe the post near the bottom will help you out, and hopefully @binhex can get that added sooner or later so this will work natively on pis without the need to do what that comment says to do.

**Comment by binhex** [comment]
there is currently no arm support for this docker image, thus the error.
