### ISSUE TITLE
Container stuck on /root/wireguardup.sh due to DNS resolution failure

### ISSUE THREAD

**Issue by iorv3th** [binhex/arch-qbittorrentvpn#97]
NOTE: Attached file is `.txt`  just for sharing purposes. The file is `.yml` on my server.

Earlier today, I installed Wireguard on Ubuntu Server 20.04 LTS in an attempt to switch over from OpenVPN. The first boot of this container worked flawlessly and download speeds were much higher than with OpenVPN. However, since that first boot the container refuses to work. No response from `dig` or from `trill`. I have another container with the same wg0.conf file that is working flawlessly (after multiple stop/start of container).

docker-compose file attached and output of some system commands are below.

[qb-docker-compose.txt](https://github.com/binhex/arch-qbittorrentvpn/files/6843456/qb-docker-compose.txt)

`uname -a`
> Linux ubuntu-server 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

`cat /etc/os-release`
> NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

`wg -v`
> wireguard-tools v1.0.20200513 - https://git.zx2c4.com/wireguard-tools/

@binhex I'm not an expert, but I can follow instructions. What else can I provide here to make your job easier?

**Comment by KnifeFed** [comment]
I believe I'm having a similar issue. Did you resolve this?
